### ISSUE TITLE
Anyone get moving platforms to work?

### ISSUE THREAD

**Issue by LukeSanderson18** [prime31/CharacterController2D#11]
Been messing around with all sorts of scripts to no avail. Dyou reckon we can just do a simple parenting to floor job?

**Comment by aidinzolghadr** [comment]
Any one achieved this?

**Comment by prime31** [comment]
Yup. Just follow any of the strategies that work for the normal CharacterController such as parenting to a moving platform or adding it's velocity to the characters.  

Mike


On Aug 16, 2015, at 6:44 AM, Aidin Zolghadr <notifications@github.com> wrote:

Any one achieved this?

**Comment by aidinzolghadr** [comment]
Problem with adding moving platform's speed is the order. I'm not sure whether you should add it's speed before or after to the characters but:

A) The order I think is important.
B) How can I make sure it happens with the order I want?

Also, which way do you think is better, parenting or adding velocity? A user previously claims that parenting causes a collision problem.

**Comment by aidinzolghadr** [comment]
I've done both ways but

A) Parenting won't help me because I need to jump from the moving platform and need to add it's speed to character. Also when shooting.

B) I tried to do it manually and when I add moving platform's speed to velocity component, as the platform goes up, character slowly goes inside the platform.

Any idea?
