### ISSUE TITLE
Collision issues when character collides with corner of platform

### ISSUE THREAD

**Issue by RyanNielson** [prime31/CharacterController2D#6]
I have the CharacterController2D script on a character. In my test level I have some 2d colliders that are set as the ground. If I jump diagonally into a corner of the collider with my character, my character clips through the platform like in the picture attached. I'm assuming this is because rays are sent out vertically and horizontally, and I'm hitting right on my character's corner.

Blue block on the right jumped and corner hit the platformer, causing him to clip through and get stuck within the platform.
![capture](https://f.cloud.github.com/assets/794694/1795167/7e8911b8-69ee-11e3-89a2-a6dcd4c783c3.PNG)

**Comment by savethejets** [comment]
I dug into this more since I was still getting this issue...

If you're using Tk2dTilemaps the way Tk2d creates the physics colliders is by creating a bunch of edge colliders. 

Unfortunately if the CharacterController falls in between the edge colliders there is no "volume" to speak of and the ray casts will treat the inside of the edge as the ground.

I would say this is actually a flaw with tk2d and not with the CharacterController. 

Any thoughts on a way to prevent this with our ray casts? Another way would be for tk2d to use polygon or box colliders instead...

**Comment by prime31** [comment]
Perhaps doing a diagonal raycast from the forward corner's position before movement to its position after movement would do the trick. 

Mike


On Jan 29, 2015, at 10:53 PM, Kyle Reczek <notifications@github.com> wrote:

I dug into this more since I was still getting this issue...

If you're using Tk2dTilemaps the way Tk2d creates the physics colliders is by creating a bunch of edge colliders.

Unfortunately if the CharacterController falls in between the edge colliders there is no "volume" to speak of and the ray casts will treat the inside of the edge as the ground.

I would say this is actually a flaw with tk2d and not with the CharacterController.

Any thoughts on a way to prevent this with our ray casts? Another way would be for tk2d to use polygon or box colliders instead...
