### ISSUE TITLE
Inconsistent jump height

### ISSUE THREAD

**Issue by midnightwalker** [prime31/CharacterController2D#66]
I have tested this character controller in Update and FixedUpdate. Example is done with Update. If you use Update in the same way as in example you are calculating physics (velocity) in Update and it causes inconsistent jump height values. Jump will go different height. Low fps is worst and if you change time scale you can notice it very well.

This problem is fixed by using FixedUpdate. But If I use FixedUpdate I have hard times to make smooth camera follow script. I have to update camera position then in FixedUpdate and it will cause some roughness for camera moving. Camera position should be updated in LateUpdate but if I follow character which position is updated in FixedUpdate then character is flickering.

Have anyone had this kind of problems and if so how have you solved it? Inconsistent jumping is not acceptable and I have not found solution for camera problem if I have to use FixedUpdate there.

**Comment by prime31** [comment]
This doesn't have anything to do with the CharacterController2D. If you search around the web there are plenty of articles on how to implement frame rate independent movement.

**Comment by midnightwalker** [comment]
Sorry if my question were improper. Thank you for your reply. Have to try to find some of those articles. We are making pixel perfect game so this jump height is really big issue at the moment. I'm used to do movement in FixedUpdate and have not face so big camera issues before than we have in this project. Movement in Update and camera movement in LateUpdate is good for camera but it will cause movement problems. I think it's related to inaccuracy of Time.deltaTime. But have to look more our code and some articles. I would suggest some kind of mention about that thing in readme of CharacterController2D. Now example is done in Update so many can miss that point totally.

**Comment by prime31** [comment]
The example is done in Update because that is the proper way to make a platformer. FixedUpdate should be used only for dealing with the actual Physics system which no real platformer should be using. When using Update you are guaranteed that your code will run every time before rendering appears so you are 100% in control. Additionally, Input is read only before Update is called so it is the only way to accurately respond to input. 

Mike


On Dec 4, 2015, at 2:07 AM, Mikko Korpinen <notifications@github.com> wrote:

Sorry if my question were improper. Thank you for your reply. Have to try to find some of those articles. We are making pixel perfect game so this jump height is really big issue at the moment. I'm used to do movement in FixedUpdate and have not face so big camera issues before than we have in this project. Movement in Update and camera movement in LateUpdate is good for camera but it will cause movement problems. I think it's related to inaccuracy of Time.deltaTime. But have to look more our code and some articles. I would suggest some kind of mention about that thing in readme of CharacterController2D. Now example is done in Update so many can miss that point totally.

**Comment by snugsound** [comment]
I'm actually running into this same issue as well:

I've tuned the jump height of my player to just slightly ABOVE 2 tiles/blocks (or 8 "units"). This works fine on my main development system, but when I test on my laptop (lower specs, especially the video card), the player jumps just shy of 2 blocks.

I agree with prime31 that this isn't an issue with CC2D. The sample code is doing it the (conventionally) "right" way, scaling movement by Time.deltaTime in Update. 

The problem is that this approach will never guarantee the player will jump EXACTLY "x.xxx" units (down to the exact decimal place). 

The only way to achieve this, as far as I know, is through using a fixed time-step. 

Using FixedUpdate will effectively allow you to achieve this, but it's a trade off: you'll run into other types of issues (jerkier movement, slower movement under heavy load, etc.).

In any case, I would NEVER handle something like camera movement in FixedUpdate. Always do that in Update, scaled by Time.deltaTime. You generally want to tie anything that's "visible" (such as camera movement) to the actual frame rate, which Update will do. 

I haven't decided if I'm going to try to fix this issue in my game; one could argue my laptop doesn't meet the "minimum system requirements", so I may just leave it as is.

**Comment by prime31** [comment]
There are most certainly strategies to get pixel perfect jump height without resorting to a fixed timestep. I have never once used fixed timestep for anything at all that isn't physics related. Do a quick Google search on the topic and you will find several solutions. The most simple approach is to just use the basic kinematic equations for movement which take velocity and acceleration into account which results in high accuracy even with a low framerate.

Mike


On Dec 4, 2015, at 9:18 AM, snugsound <notifications@github.com> wrote:

I'm actually running into this same issue as well:

I've tuned the jump height of my player to just slightly ABOVE 2 tiles/blocks (or 8 "units"). This works fine on my main development system, but when I test on my laptop (lower specs, especially the video card), the player jumps just shy of 2 blocks.

I agree with prime31 that this isn't an issue with CC2D. The sample code is doing it the (conventionally) "right" way, scaling movement by Time.deltaTime in Update.

The problem is that this approach will never guarantee the player will jump EXACTLY "x.xxx" units (down to the exact decimal place).

The only way to achieve this, as far as I know, is through using a fixed time-step.

Using FixedUpdate will effectively allow you to achieve this, but it's a trade off: you'll run into other types of issues (jerkier movement, slower movement under heavy load, etc.).

In any case, I would NEVER handle something like camera movement in FixedUpdate. Always do that in Update, scaled by Time.deltaTime. You generally want to tie anything that's "visible" (such as camera movement) to the actual frame rate, which Update will do.

I haven't decided if I'm going to try to fix this issue in my game; one could argue my laptop doesn't meet the "minimum system requirements", so I may just leave it as is.

**Comment by snugsound** [comment]
Mike, do you have any practical examples you could link me to? A (less than quick) Google search didn't yield any obvious results.

Is the issue here not that finite precision in a variable time-step is inherently imprecise and will not reproduce consistent results? Everything I've ever read suggests this. If this were not the case then why are physics engines implemented using a fixed time-step? i.e. http://gafferongames.com/game-physics/fix-your-timestep/

Please prove me wrong, I would like there to be a simple solution to this :)

**Comment by prime31** [comment]
A quick Google turns up this link (http://stackoverflow.com/questions/17263580/how-do-i-keep-the-jump-height-the-same-when-using-delta-time) which has a pretty good explanation and pseudo code to solve the problem. 

Mike


On Dec 5, 2015, at 7:56 AM, snugsound <notifications@github.com> wrote:

Mike, do you have any practical examples you could link me to? A (less than quick) Google search didn't yield any obvious results.

Is the issue here not that finite precision in a variable time-step is inherently imprecise and will not reproduce consistent results? Everything I've ever read suggests this. If this were not the case then why are physics engines implemented using a fixed time-step? i.e. http://gafferongames.com/game-physics/fix-your-timestep/

Please prove me wrong, I would like there to be a simple solution to this :)

**Comment by midnightwalker** [comment]
I don't see why platformer proper way to do is in Update. How ever I see it is best for rendering. So if rendering is top priority then it is correct way to do it. I would count rendering and movement into same priority level. Have to get both of those right. Quick look to stackoverflow http://stackoverflow.com/questions/17263580/how-do-i-keep-the-jump-height-the-same-when-using-delta-time post did not offer any real solution of the problem. Have to try it but it seems like it's only doing same thing slightly different. Maybe the result is bit more accuracy but not perfect. But thanks for your time and help.
